# Generated by Django 6.0.1 on 2026-02-25 00:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('event_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('country', models.CharField(max_length=150)),
                ('region', models.CharField(help_text='East Africa, Africa, Worldwide (aggregated allowed)', max_length=150)),
                ('county', models.CharField(blank=True, help_text='Specific to Kenya', max_length=150)),
                ('city', models.CharField(blank=True, max_length=150)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('category', models.CharField(max_length=150)),
                ('era', models.CharField(blank=True, max_length=150)),
                ('impact_level', models.CharField(choices=[('local', 'Local'), ('national', 'National'), ('continental', 'Continental'), ('global', 'Global')], default='national', max_length=20)),
                ('summary', models.TextField(help_text='Short 2–4 sentence overview')),
                ('description', models.TextField()),
                ('full_story', models.TextField()),
                ('quote_text', models.TextField(blank=True)),
                ('quote_author', models.CharField(blank=True, max_length=255)),
                ('quote_source', models.CharField(blank=True, max_length=255)),
                ('verification_status', models.CharField(choices=[('draft', 'Draft'), ('reviewed', 'Reviewed'), ('verified', 'Verified')], default='draft', max_length=20)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('restricted', 'Restricted')], default='public', max_length=20)),
                ('featured', models.BooleanField(default=False)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-event_date'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('photo', 'Photo'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Document')], max_length=20)),
                ('file', models.FileField(upload_to='archives/media/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('archive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='ReelRoots_app.archive')),
            ],
        ),
        migrations.AddField(
            model_name='archive',
            name='tags',
            field=models.ManyToManyField(blank=True, to='ReelRoots_app.tag'),
        ),
    ]
