# Generated by Django 6.0.2 on 2026-07-22 12:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReelRoots_app', '0002_auth_personalization'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creator_name', models.CharField(max_length=150)),
                ('creator_handle', models.CharField(blank=True, max_length=150)),
                ('original_creator_name', models.CharField(blank=True, max_length=150)),
                ('source_platform', models.CharField(choices=[('native', 'ReelRoots'), ('pexels', 'Pexels'), ('youtube', 'YouTube'), ('vimeo', 'Vimeo'), ('archive', 'Archive'), ('other', 'Other')], max_length=32)),
                ('external_id', models.CharField(blank=True, max_length=255)),
                ('source_url', models.URLField(blank=True)),
                ('video_url', models.URLField()),
                ('thumbnail_url', models.URLField(blank=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('source_attribution', models.CharField(blank=True, max_length=255)),
                ('license_status', models.CharField(choices=[('owned', 'Owned'), ('licensed', 'Licensed'), ('public_domain', 'Public domain'), ('permitted_embed', 'Permitted embed'), ('pending_review', 'Pending review')], default='pending_review', max_length=32)),
                ('content_type', models.CharField(choices=[('native', 'Native ReelRoots video'), ('creator', 'Creator upload'), ('licensed', 'Licensed content'), ('public_domain', 'Public-domain footage'), ('embed', 'Permitted embed'), ('curated_external', 'Curated external media')], default='curated_external', max_length=32)),
                ('heritage_relevance', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('geographic_relevance', models.CharField(blank=True, max_length=150)),
                ('verification_status', models.CharField(choices=[('unreviewed', 'Unreviewed'), ('reviewed', 'Reviewed'), ('verified', 'Verified'), ('disputed', 'Disputed')], default='unreviewed', max_length=20)),
                ('confidence_score', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('quality_score', models.DecimalField(decimal_places=4, default=0.5, max_digits=5)),
                ('context_summary', models.TextField(blank=True)),
                ('key_claims', models.JSONField(blank=True, default=list)),
                ('historical_context', models.TextField(blank=True)),
                ('important_people', models.JSONField(blank=True, default=list)),
                ('important_locations', models.JSONField(blank=True, default=list)),
                ('timeline', models.JSONField(blank=True, default=list)),
                ('external_references', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('hidden', 'Hidden')], default='draft', max_length=20)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reels', to='ReelRoots_app.userprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReelComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=500)),
                ('is_hidden', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reel_comments', to='ReelRoots_app.userprofile')),
                ('reel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='ReelRoots_app.reel')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReelCreatorFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator_key', models.CharField(max_length=255)),
                ('creator_name', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_creators', to='ReelRoots_app.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ReelLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reel_likes', to='ReelRoots_app.userprofile')),
                ('reel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='ReelRoots_app.reel')),
            ],
        ),
        migrations.CreateModel(
            name='ReelReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=80)),
                ('details', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('open', 'Open'), ('reviewed', 'Reviewed'), ('dismissed', 'Dismissed')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reel_reports', to='ReelRoots_app.userprofile')),
                ('reel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='ReelRoots_app.reel')),
            ],
        ),
        migrations.CreateModel(
            name='ReelSave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reel_saves', to='ReelRoots_app.userprofile')),
                ('reel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saves', to='ReelRoots_app.reel')),
            ],
        ),
        migrations.AddIndex(
            model_name='reel',
            index=models.Index(fields=['status', 'heritage_relevance', 'created_at'], name='ReelRoots_a_status_8e9e4d_idx'),
        ),
        migrations.AddIndex(
            model_name='reel',
            index=models.Index(fields=['source_platform', 'external_id'], name='ReelRoots_a_source__85f7e6_idx'),
        ),
        migrations.AddConstraint(
            model_name='reel',
            constraint=models.UniqueConstraint(fields=('source_platform', 'external_id'), name='unique_reel_external_source'),
        ),
        migrations.AddIndex(
            model_name='reelcomment',
            index=models.Index(fields=['reel', 'created_at'], name='ReelRoots_a_reel_id_20c399_idx'),
        ),
        migrations.AddConstraint(
            model_name='reelcreatorfollow',
            constraint=models.UniqueConstraint(fields=('profile', 'creator_key'), name='unique_creator_follow'),
        ),
        migrations.AddConstraint(
            model_name='reellike',
            constraint=models.UniqueConstraint(fields=('reel', 'profile'), name='unique_reel_like'),
        ),
        migrations.AddConstraint(
            model_name='reelreport',
            constraint=models.UniqueConstraint(fields=('reel', 'profile'), name='unique_reel_report'),
        ),
        migrations.AddConstraint(
            model_name='reelsave',
            constraint=models.UniqueConstraint(fields=('reel', 'profile'), name='unique_reel_save'),
        ),
    ]
