# Generated by Django 6.0.2 on 2026-07-22 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReelRoots_app', '0003_reel_reelcomment_reelcreatorfollow_reellike_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reel',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='reels', to='ReelRoots_app.topic'),
        ),
    ]
