# Generated by Django 6.0.2 on 2026-07-22 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReelRoots_app', '0004_reel_topics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reel',
            name='external_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
