# Generated by Django 6.0.2 on 2026-07-22 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReelRoots_app', '0005_alter_reel_external_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('title', models.CharField(max_length=500)),
                ('publisher', models.CharField(blank=True, max_length=255)),
                ('source_type', models.CharField(choices=[('original_media', 'Original media'), ('academic', 'Academic publication'), ('archive', 'Archive'), ('museum', 'Museum'), ('university', 'University'), ('government', 'Government archive'), ('library', 'Library'), ('journalism', 'Reputable journalism'), ('cultural_institution', 'Cultural institution'), ('other', 'Other')], default='other', max_length=32)),
                ('authority_rank', models.PositiveSmallIntegerField(default=1)),
                ('license_name', models.CharField(blank=True, max_length=255)),
                ('excerpt', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('last_retrieved_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-authority_rank', 'publisher', 'title'],
            },
        ),
        migrations.AlterField(
            model_name='reel',
            name='source_platform',
            field=models.CharField(choices=[('native', 'ReelRoots'), ('pexels', 'Pexels'), ('wikimedia', 'Wikimedia Commons'), ('youtube', 'YouTube'), ('vimeo', 'Vimeo'), ('archive', 'Archive'), ('other', 'Other')], max_length=32),
        ),
        migrations.CreateModel(
            name='ReelContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcript', models.TextField(blank=True)),
                ('transcript_status', models.CharField(default='metadata_fallback', max_length=40)),
                ('summary', models.TextField(blank=True)),
                ('historical_context', models.TextField(blank=True)),
                ('key_facts', models.JSONField(blank=True, default=list)),
                ('related_topic_slugs', models.JSONField(blank=True, default=list)),
                ('external_links', models.JSONField(blank=True, default=list)),
                ('model_name', models.CharField(blank=True, max_length=120)),
                ('prompt_version', models.CharField(blank=True, max_length=40)),
                ('source_fingerprint', models.CharField(blank=True, max_length=64)),
                ('confidence_score', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('verification_status', models.CharField(choices=[('verified', 'Verified'), ('partially_supported', 'Partially supported'), ('disputed', 'Disputed'), ('insufficient_evidence', 'Insufficient evidence'), ('false_misleading', 'False or misleading')], default='insufficient_evidence', max_length=32)),
                ('generation_status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='context_document', to='ReelRoots_app.reel')),
            ],
        ),
        migrations.CreateModel(
            name='ContextTimelineEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_label', models.CharField(max_length=120)),
                ('event', models.TextField()),
                ('location', models.CharField(blank=True, max_length=255)),
                ('confidence_score', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('ordinal', models.PositiveIntegerField(default=0)),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='ReelRoots_app.reelcontext')),
            ],
            options={
                'ordering': ['ordinal', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ContextClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_text', models.TextField()),
                ('claim_type', models.CharField(choices=[('historical', 'Historical'), ('cultural', 'Cultural'), ('media', 'Media')], default='historical', max_length=20)),
                ('verification_status', models.CharField(choices=[('verified', 'Verified'), ('partially_supported', 'Partially supported'), ('disputed', 'Disputed'), ('insufficient_evidence', 'Insufficient evidence'), ('false_misleading', 'False or misleading')], default='insufficient_evidence', max_length=32)),
                ('confidence_score', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('evidence_summary', models.TextField(blank=True)),
                ('ordinal', models.PositiveIntegerField(default=0)),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='ReelRoots_app.reelcontext')),
            ],
            options={
                'ordering': ['ordinal', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ContextEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(choices=[('supports', 'Supports'), ('contradicts', 'Contradicts'), ('unclear', 'Unclear')], default='unclear', max_length=20)),
                ('excerpt', models.TextField(blank=True)),
                ('source_locator', models.CharField(blank=True, max_length=255)),
                ('confidence_score', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='ReelRoots_app.contextclaim')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='ReelRoots_app.knowledgesource')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('claim', 'source'), name='unique_claim_source_evidence')],
            },
        ),
        migrations.CreateModel(
            name='ContextEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('entity_type', models.CharField(choices=[('person', 'Person'), ('place', 'Place'), ('date', 'Date'), ('event', 'Event'), ('organization', 'Organization'), ('cultural_group', 'Cultural group')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('confidence_score', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('ordinal', models.PositiveIntegerField(default=0)),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='ReelRoots_app.reelcontext')),
            ],
            options={
                'ordering': ['entity_type', 'ordinal', 'name'],
                'constraints': [models.UniqueConstraint(fields=('context', 'entity_type', 'name'), name='unique_context_entity')],
            },
        ),
        migrations.AddIndex(
            model_name='contextclaim',
            index=models.Index(fields=['context', 'verification_status'], name='ReelRoots_a_context_8016e1_idx'),
        ),
    ]
