# Generated by Django 6.0.2 on 2026-07-22 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReelRoots_app', '0006_knowledgesource_alter_reel_source_platform_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reelcontext',
            name='sources',
            field=models.ManyToManyField(blank=True, related_name='contexts', to='ReelRoots_app.knowledgesource'),
        ),
    ]
