# Generated by Django 6.0.2 on 2026-07-22 13:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReelRoots_app', '0007_reelcontext_sources'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('input_type', models.CharField(choices=[('url', 'URL'), ('article', 'Article'), ('webpage', 'Webpage'), ('pdf', 'PDF'), ('text', 'Text'), ('video', 'Video URL'), ('image', 'Image')], max_length=20)),
                ('source_url', models.URLField(blank=True)),
                ('source_file', models.FileField(blank=True, upload_to='verification/submissions/')),
                ('input_text', models.TextField(blank=True)),
                ('content_title', models.CharField(blank=True, max_length=500)),
                ('extracted_text', models.TextField(blank=True)),
                ('content_metadata', models.JSONField(blank=True, default=dict)),
                ('content_hash', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('extracting', 'Analyzing content'), ('extracting_claims', 'Extracting claims'), ('finding_evidence', 'Finding evidence'), ('comparing_sources', 'Comparing sources'), ('preparing_results', 'Preparing results'), ('complete', 'Complete'), ('failed', 'Failed')], default='queued', max_length=32)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('status_message', models.CharField(blank=True, max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_requests', to='ReelRoots_app.userprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VerificationClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_text', models.TextField()),
                ('claim_type', models.CharField(choices=[('factual', 'Factual'), ('historical', 'Historical'), ('cultural', 'Cultural'), ('subjective', 'Subjective')], default='factual', max_length=20)),
                ('assessment', models.CharField(choices=[('supported', 'Supported'), ('mostly_supported', 'Mostly supported'), ('partially_supported', 'Partially supported'), ('disputed', 'Disputed'), ('unsupported', 'Unsupported'), ('misleading', 'Misleading'), ('false', 'False'), ('unable_to_verify', 'Unable to verify'), ('subjective', 'Subjective')], default='unable_to_verify', max_length=32)),
                ('confidence_score', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('reasoning', models.TextField(blank=True, help_text='Concise user-facing reasoning, never chain-of-thought.')),
                ('entities', models.JSONField(blank=True, default=list)),
                ('topic_slugs', models.JSONField(blank=True, default=list)),
                ('ordinal', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='ReelRoots_app.verificationrequest')),
            ],
            options={
                'ordering': ['ordinal', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VerificationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_assessment', models.CharField(choices=[('supported', 'Supported'), ('mostly_supported', 'Mostly supported'), ('partially_supported', 'Partially supported'), ('disputed', 'Disputed'), ('unsupported', 'Unsupported'), ('misleading', 'Misleading'), ('false', 'False'), ('unable_to_verify', 'Unable to verify'), ('subjective', 'Subjective')], default='unable_to_verify', max_length=32)),
                ('confidence_score', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('summary', models.TextField(blank=True)),
                ('historical_context', models.TextField(blank=True)),
                ('explanation', models.TextField(blank=True)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('entities', models.JSONField(blank=True, default=list)),
                ('topic_slugs', models.JSONField(blank=True, default=list)),
                ('model_name', models.CharField(blank=True, max_length=120)),
                ('prompt_version', models.CharField(blank=True, max_length=40)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='ReelRoots_app.verificationrequest')),
            ],
        ),
        migrations.CreateModel(
            name='VerificationEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(choices=[('supports', 'Supporting evidence'), ('contradicts', 'Contradicting evidence'), ('unclear', 'Unclear evidence')], default='unclear', max_length=20)),
                ('excerpt', models.TextField(blank=True)),
                ('source_locator', models.CharField(blank=True, max_length=255)),
                ('relevance_score', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('quality_score', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('comparison_note', models.TextField(blank=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='ReelRoots_app.verificationclaim')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_evidence', to='ReelRoots_app.knowledgesource')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('claim', 'source'), name='unique_verification_claim_source')],
            },
        ),
        migrations.AddIndex(
            model_name='verificationrequest',
            index=models.Index(fields=['profile', 'status', 'created_at'], name='ReelRoots_a_profile_289b8c_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationrequest',
            index=models.Index(fields=['content_hash', 'status'], name='ReelRoots_a_content_d6e782_idx'),
        ),
        migrations.AddIndex(
            model_name='verificationclaim',
            index=models.Index(fields=['request', 'assessment'], name='ReelRoots_a_request_e86681_idx'),
        ),
    ]
