# Generated by Django 6.0.2 on 2026-07-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReelRoots_app', '0008_verificationrequest_verificationclaim_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationrequest',
            name='source_url',
            field=models.URLField(blank=True, max_length=2000),
        ),
    ]
