# Generated by Django 6.0.2 on 2026-07-22 14:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReelRoots_app', '0009_alter_verificationrequest_source_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_moderator',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ContributorSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=120)),
                ('country', models.CharField(max_length=150)),
                ('region', models.CharField(max_length=150)),
                ('cultural_context', models.TextField()),
                ('source_reference', models.URLField(blank=True, max_length=2000)),
                ('source_notes', models.TextField(blank=True)),
                ('permission_type', models.CharField(choices=[('owned', 'I own this content'), ('licensed', 'I have a license'), ('public_domain', 'Public domain'), ('permission', 'I have permission'), ('pending', 'Permission needs review')], default='pending', max_length=20)),
                ('permission_details', models.TextField(blank=True)),
                ('transcript', models.TextField(blank=True)),
                ('media_file', models.FileField(upload_to='contributor/submissions/')),
                ('thumbnail_file', models.FileField(blank=True, upload_to='contributor/thumbnails/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('processing', 'Processing'), ('needs_review', 'Needs Review'), ('approved', 'Approved'), ('published', 'Published'), ('rejected', 'Rejected'), ('flagged', 'Flagged'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=12)),
                ('risk_score', models.DecimalField(decimal_places=4, default=0.5, max_digits=5)),
                ('risk_reasons', models.JSONField(blank=True, default=list)),
                ('ai_summary', models.TextField(blank=True)),
                ('moderation_notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributor_submissions', to='ReelRoots_app.userprofile')),
                ('reel', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributor_submission', to='ReelRoots_app.reel')),
                ('verification_request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submission', to='ReelRoots_app.verificationrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContributorTrustProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('viewer', 'Viewer'), ('contributor', 'Contributor'), ('verified_contributor', 'Verified Contributor'), ('heritage_partner', 'Heritage Partner')], default='viewer', max_length=32)),
                ('score', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('confidence', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('component_scores', models.JSONField(blank=True, default=dict)),
                ('explanation', models.JSONField(blank=True, default=list)),
                ('calculated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trust_profile', to='ReelRoots_app.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ContributorTrustSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_type', models.CharField(choices=[('accuracy', 'Accuracy history'), ('quality', 'Content quality'), ('community_report', 'Community report'), ('moderator_decision', 'Moderator decision'), ('source_quality', 'Source quality'), ('account_age', 'Account age'), ('engagement', 'Engagement pattern')], max_length=32)),
                ('value', models.DecimalField(decimal_places=4, max_digits=6)),
                ('weight', models.DecimalField(decimal_places=4, default=1, max_digits=6)),
                ('explanation', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trust_signals', to='ReelRoots_app.userprofile')),
                ('submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trust_signals', to='ReelRoots_app.contributorsubmission')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModerationAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('action', models.CharField(max_length=80)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_actions', to='ReelRoots_app.userprofile')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_history', to='ReelRoots_app.contributorsubmission')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=100)),
                ('details', models.CharField(blank=True, max_length=1000)),
                ('status', models.CharField(choices=[('open', 'Open'), ('reviewed', 'Reviewed'), ('dismissed', 'Dismissed')], default='open', max_length=20)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_reports', to='ReelRoots_app.userprofile')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_submission_reports', to='ReelRoots_app.userprofile')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='ReelRoots_app.contributorsubmission')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='contributorsubmission',
            index=models.Index(fields=['status', 'risk_level', 'created_at'], name='ReelRoots_a_status_f3880d_idx'),
        ),
        migrations.AddIndex(
            model_name='contributorsubmission',
            index=models.Index(fields=['profile', 'status', 'created_at'], name='ReelRoots_a_profile_c756ed_idx'),
        ),
        migrations.AddIndex(
            model_name='contributortrustsignal',
            index=models.Index(fields=['profile', 'signal_type', 'created_at'], name='ReelRoots_a_profile_5b05a7_idx'),
        ),
        migrations.AddConstraint(
            model_name='submissionreport',
            constraint=models.UniqueConstraint(fields=('submission', 'profile'), name='unique_submission_report'),
        ),
    ]
